name: listahan
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.8.0
  flutter_hooks: ^0.18.6
  form_builder_validators: ^8.5.0
  intl: ^0.17.0
  path: ^1.8.2
  path_provider: ^2.0.13
  drift: ^2.5.0
  sqlite3_flutter_libs: ^0.5.0
  rxdart: ^0.27.7
  dropdown_search:
  flutter_native_splash:
  flutter_spinbox: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.5.2
  build_runner: ^2.3.3
  flutter_launcher_icons: "^0.12.0"

flutter:
  uses-material-design: true
